---
name: 'Build Hugo Website'

on:
  workflow_call:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.88.1'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: public
        path: public/