---
name: 'Build goHugo.ai Website for ZeroHunger.ai'

on:
  workflow_call:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref_name, 'v') && contains(github.ref_name, '-rc') && 'qa' || 'www' }}
    #using: 'composite'
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.88.1'
        extended: true

    - name: Build
      run: |
        cd ZeroHunger.ai
        hugo --minify

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: public
        path: ZeroHunger.ai/public/