
---
  name: 'Deploy Docker Containers'

  on:
    workflow_call:
    workflow_dispatch:

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ vars.SSH_FINGERPRINT }}

      - name: Create docker context
        run: docker context create prod --docker "host=ssh://${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}"

      - name: Deploy Docker Containers
        run: |
          docker-compose --context prod -f docker-compose.yml up --build --remove-orphans -d
        env:
          HUGO_ENV: production
