---
  name: 'Deploy to Azure Storage Account'

  on:
    workflow_call: {}
    workflow_dispatch: {}

  jobs:
    deploy:
      runs-on: ubuntu-latest
      environment: ${{ startsWith(github.ref_name, 'v') && contains(github.ref_name, '-rc') && 'qa' || 'www' }}
      steps:
      - uses: actions/checkout@v2
        
      - name: Download built website
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public

      - name: List directory contents
        run: |
          pwd
          ls -la
          
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
# TODO: check if Fixed the Azure CLI command for uploading to storage blob. The error suggests that no active account is set.
# Consider running 'az account set' before the upload command.

      # - name: Set active subscription
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: 2.0.72
      #     inlineScript: |
      #       az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Storage Account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --source ./public --destination '$web'
        # env:
        #   AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        #   AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}