---
name: 'Deploy to Azure Storage Account'

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref_name, 'v') && contains(github.ref_name, '-rc') && 'qa' || 'prod' }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Download built website
        uses: actions/download-artifact@v3
        with:
          name: public
          path: ./public

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Deploy to Azure Storage Account
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --source ./public \
              --destination '$web' \
              --overwrite true \
              --auth-mode login
