---
  name: 'Deploy to Azure Storage Account'

  on:
    workflow_call: {}
    workflow_dispatch: {}

  jobs:
    deploy:
      runs-on: ubuntu-latest
      environment: ${{ startsWith(github.ref_name, 'v') && contains(github.ref_name, '-rc') && 'qa' || 'www' }}
      steps:
      - uses: actions/checkout@v2
        
      - name: Download built website
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public

      - name: List directory contents
        run: |
          pwd
          ls -la *
          
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Deploy to Azure Storage Account
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --overwrite true --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --source ./public --destination '$web'
