---
  name: 'Setup Storage Account and DNS for Website'

  on:
    workflow_call: {}
    workflow_dispatch: {}
  
  # on:
  #   workflow_dispatch:
  #     inputs:
  #       environment:
  #         description: 'Environment (qa or www)'
  #         required: true
  
  jobs:
    Storage:
      runs-on: ubuntu-latest
      using: 'composite'
      steps:
      - name: Check if environment is set up through setup.sh
        run: |
          if [[ -z "${{ env.AZURE_SERVICE_PRINCIPAL }}" || -z "${{ env.AZURE_SUBSCRIPTION_ID }}" || -z "${{ env.AZURE_STORAGE_ACCOUNT_NAME }}" ]]; then
            echo "Please run az_setup.sh first to set up the environment and secrets."
            exit 1
          fi
  
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_SERVICE_PRINCIPAL }}
  
      - name: Create storage account and setup for static website hosting
        run: |
          az storage account create --name ${{ env.AZURE_STORAGE_ACCOUNT_NAME }} --resource-group $resourceGroupName --location $location --sku Standard_LRS --auth-mode login
          az storage blob service-properties update --account-name ${{ env.AZURE_STORAGE_ACCOUNT_NAME }} --static-website --404-document 404.html --index-document index.html --auth-mode login


    # DNS:
    #   runs-on: ubuntu-latest
    #   steps:
    #   - uses: actions/checkout@v2

    #   - name: Azure login
    #     uses: azure/login@v1
    #     with:
    #       creds: ${{ env.AZURE_SERVICE_PRINCIPAL }}

    #   - name: Create Resource Group
    #     uses: azure/CLI@v1
    #     with:
    #       azcliversion: 2.0.72
    #       inlineScript: |
    #         az group create --name zerohunger-qa-rg --location eastus

    #   - name: Create Key Vault
    #     uses: azure/CLI@v1
    #     with:
    #       azcliversion: 2.0.72
    #       inlineScript: |
    #         az keyvault create --name zerohungerqakeyvault --resource-group zerohunger-qa-rg --location eastus

    #   - name: Setup DNS
    #     uses: azure/CLI@v1
    #     with:
    #       azcliversion: 2.0.72
    #       inlineScript: |
    #         az network dns zone create --name zerohunger.ai --resource-group zerohunger-qa-rg
    #         az network dns record-set cname add-record --resource-group zerohunger-qa-rg --zone-name zerohunger.ai --record-set-name qa --cname zerohungerqastorage.z6.web.core.windows.net
