---
name: 'Verify Infrastructure'

on:
  workflow_call: {}
  workflow_dispatch: {}
  
jobs:
  verify:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref_name, 'v') && contains(github.ref_name, '-rc') && 'qa' || 'prod' }}
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Verify storage account
        run: |
          if ! az storage account show --name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} &>/dev/null; then
            echo "Storage account ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} does not exist"
            exit 1
          fi
          
          if ! az storage blob service-properties show --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --query "staticWebsite.enabled" -o tsv | grep -q "true"; then
            echo "Static website hosting not enabled on ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
            exit 1
          fi
