name: 'build, release and deploy'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v*-rc[0-9]+'

jobs:
  pipeline:
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml

      - name: Infrastructure
        uses: ./.github/workflows/infrastructure.yml
        env:
          AZURE_SERVICE_PRINCIPAL: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}

      - name: Deploy
        uses: ./.github/workflows/deploy.yml
        env:
          AZURE_SERVICE_PRINCIPAL: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}